"""3D modeling via Blender. REYES writes a Blender-Python (bpy) snippet
that builds the geometry; this tool wraps it in a scene scaffold (clean
scene, camera, lights, render settings), runs Blender headless, and saves
a rendered PNG you can look at -- plus the .blend so you can open/edit it.

Honest scope: this is real but bounded. bpy scripting is great for
procedural/parametric things -- primitives, arrays, simple architecture,
props, logos-in-3D, basic animation frames -- not arbitrary photoreal
hero assets. "Almost anything" means almost anything you could script,
not a movie studio.

Gated (requires_confirmation) because it runs generated Python inside
Blender -- same tier as run_command.
"""

from __future__ import annotations

import os
import subprocess
import tempfile
import time

from reyes_agent import config
from reyes_agent.tools import register

_OUT_DIR = config.VAULT_PATH / "07-System" / "3d"

_BLENDER_CANDIDATES = [
    r"C:\Program Files\Blender Foundation\Blender 5.2\blender.exe",
]


def _find_blender() -> str | None:
    for p in _BLENDER_CANDIDATES:
        if os.path.isfile(p):
            return p
    # any installed version under the standard folder
    import glob

    for p in glob.glob(r"C:\Program Files\Blender Foundation\*\blender.exe"):
        return p
    return None


_SCAFFOLD = '''
import bpy, math, os

# --- clean slate ---
bpy.ops.object.select_all(action='SELECT')
bpy.ops.object.delete(use_global=False)

# --- user geometry (generated by REYES) ---
{user_code}

# --- ensure there's a camera ---
if bpy.context.scene.camera is None:
    bpy.ops.object.camera_add(location=(7.0, -7.0, 5.0))
    cam = bpy.context.object
    cam.rotation_euler = (math.radians(60), 0.0, math.radians(45))
    bpy.context.scene.camera = cam

# --- a key light ---
bpy.ops.object.light_add(type='SUN', location=(6.0, -4.0, 10.0))
bpy.context.object.data.energy = 4.0

# --- render settings ---
scene = bpy.context.scene
scene.render.resolution_x = 960
scene.render.resolution_y = 720
scene.render.film_transparent = False
scene.render.filepath = r"{render_path}"
bpy.ops.render.render(write_still=True)

# --- save the editable .blend too ---
bpy.ops.wm.save_as_mainfile(filepath=r"{blend_path}")
'''


@register(
    name="create_3d_model",
    description=(
        "Create a 3D model with Blender and render it to an image. You "
        "provide `bpy_code`: Blender-Python that builds the geometry (e.g. "
        "bpy.ops.mesh.primitive_uv_sphere_add(...), loops, modifiers, "
        "materials). A scene scaffold (clean scene, camera, light, render) "
        "is added automatically -- just write the geometry. Good for "
        "procedural/parametric models, props, simple scenes and logos in "
        "3D. Requires the user's approval (it runs generated Python in "
        "Blender)."
    ),
    input_schema={
        "type": "object",
        "properties": {
            "bpy_code": {"type": "string", "description": "Blender-Python building the geometry (no camera/render needed)."},
            "name": {"type": "string", "description": "Short name for the output files."},
        },
        "required": ["bpy_code"],
    },
    requires_confirmation=True,
)
def create_3d_model(bpy_code: str, name: str = "model") -> str:
    blender = _find_blender()
    if not blender:
        return "Blender isn't installed where I expected -- couldn't find blender.exe."

    _OUT_DIR.mkdir(parents=True, exist_ok=True)
    safe = "".join(c for c in name if c.isalnum() or c in "-_") or "model"
    stamp = time.strftime("%Y%m%d-%H%M%S")
    render_path = _OUT_DIR / f"{safe}-{stamp}.png"
    blend_path = _OUT_DIR / f"{safe}-{stamp}.blend"

    script = _SCAFFOLD.format(
        user_code=bpy_code,
        render_path=str(render_path),
        blend_path=str(blend_path),
    )
    with tempfile.NamedTemporaryFile("w", suffix=".py", delete=False, encoding="utf-8") as f:
        f.write(script)
        script_path = f.name

    try:
        proc = subprocess.run(
            [blender, "--background", "--python", script_path],
            capture_output=True, text=True, timeout=180,
        )
    except subprocess.TimeoutExpired:
        return "Blender timed out (over 3 min) -- the model may be too heavy."
    finally:
        try:
            os.unlink(script_path)
        except OSError:
            pass

    if render_path.exists():
        return f"Rendered a 3D model to {render_path} (editable .blend at {blend_path})."
    # surface the real Blender error so a bad script can be fixed
    err = (proc.stderr or proc.stdout or "").strip()[-800:]
    return f"Blender ran but produced no image. Output:\n{err}"
